language: android
jdk: oraclejdk8
# See https://github.com/travis-ci/travis-ci/issues/5582
sudo: required
android:
  components:
    - tools
    - tools
before_script:
  - echo y | ${ANDROID_HOME}tools/bin/sdkmanager --channel=3 "tools" "platform-tools" "build-tools;26.0.2" "platforms;android-27" "extras;google;m2repository" "extras;google;google_play_services"
script: ./gradlew clean assemble lint